name: MSRV

# read-only repo token
# no access to secrets
on:
  push:
    branches: [ master ]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  verify-build:
    runs-on: ubuntu-latest

    steps:
    # checkout repo
    - uses: actions/checkout@v3

    - name: Install rust
      # Aligned with `rust-version` in `Cargo.toml`
      uses: dtolnay/rust-toolchain@1.63

    - name: Generate Cargo.lock
      run: cargo generate-lockfile

    # restore cargo cache from previous runs
    - name: Rust Cache
      uses: Swatinem/rust-cache@v2
      with:
        # The cache should not be shared between different workflows and jobs.
        shared-key: ${{ github.workflow }}-${{ github.job }}

    # check it builds
    - name: Build
      run: cargo build --locked --verbose --all-targets --all-features
