name: Build

# read-only repo token
# no access to secrets
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  verify-build:
    runs-on: ubuntu-latest

    steps:
    # checkout repo
    - uses: actions/checkout@v3

    - name: Install rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt, clippy

    # check it builds
    - name: Build
      run: cargo build --verbose --all-targets --all-features

    # run tests
    - name: Run tests
      run: cargo test --verbose --all-features

    # make sure all code has been formatted with rustfmt
    - name: check rustfmt
      run: cargo fmt -- --check --color always

    # run clippy to verify we have no warnings
    - name: cargo clippy
      run: cargo clippy --all-targets --all-features

    # check for rustdoc warnings
    - name: generate and verify rustdoc
      env:
        RUSTDOCFLAGS: -D warnings
      run: cargo doc --no-deps --document-private-items --workspace --all-features
